### ISSUE TITLE
Upgrade to React 16

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-react#418]
This is going to be non-trivial. Hopefully not a big deal either.

For those salivating and pining in anticipating for this, I *hope* to get it done this month but no promises (I have a family to support).

Also it will come out in v1.2.0. Before then there'll be a minor release still on React 15.

*Edit: Not committing to a timeline but these are the changes:*

# Changes & Progress

* New render return types
  * [x] arrays
  * [x] strings
  * [x] numbers
  * [x] portals
  * [x] null (how does sjr handle this? should we bother supporting it anyway?) -- don't support; THIS. IS. SCAALAAA!
  * [x] `EmptyVdom` (Scala version of above)
  * [x] boolean (to support JS syntax *bool && expr* - should we support this? it's ≈ null, even when true) -- don't support; THIS. IS. SCAALAAA!
  * [x] `Option[_]` (Scala version of above)
  * [x] fragments
* [x] Fragments
* Portals
  * [x] `ReactDOM.createPortal`
  * [x] React.Children support for portals (https://github.com/facebook/react/issues/11373)
* "Error boundaries"
  * [x] `componentDidCatch`
* React Addons have been discontinued
  * [x] `react-addons-test-utils` is now `react-dom/test-utils`
  * [x] `perf` doesn't work with 16 - no replacement yet
  * [x] `react-addons-css-transition-group` is now `react-transition-group`, a separate lib
* Deprecated now removed
  * [x] `createClass`
* VDOM
  * [x] Allow on as a custom attribute for AMP. https://github.com/facebook/react/issues/11153
  * [x] Remove VdomElement? -- Nope, still needed by `ReactDOM`
* Other
  * [x] New rules for Keys
  * [x] New rules for Refs
  * [x] `getDOMNode` should now return `Element | Text` instead of just `Element`
  * [x] Refresh vdom builder prod-mode logic
  * [x] Refresh component builder logic
  * [x] componentDidUpdate lifecycle no longer receives prevContext param. See https://github.com/facebook/react/issues/8631 (Don't think sjr is affected)
  * [ ] Remember to test module paths with sjs-bundler -- *wasted enough time trying to get fragile bundler to even run my tests*
  * [x] Depends on requestAnimationFrame (even in test environments). Might need shim: `import 'raf/polyfill'`

Externalised
  * #448 - Calling `setState` with null no longer triggers an update.
  * #449 - Update docs

**Comment by japgolly** [comment]
https://twitter.com/japgolly/status/933118294705422336

> Would anyone be interested in sponsoring me to update #scalajs-#react to React 16?
>
> Context: I've never been paid any of my time on OSS; all of my OSS work I've done at the cost of other paying work. React16 is non-trivial and I doubt I'll be able to do it for free for a while.

I envision 3 outcomes here.

1. I get sponsored and add React 16 support.
2. Community member(s) contribute React 16 support (understanding that the review process might be a little slow).
3. We all wait until next year and likely Q2/Q3 at that.

**Comment by japgolly** [comment]
And to those of you reading this because you've subscribed because you love the project, you're probably disappointed and I'm sorry for that. It will definitely happen, externally, it's just a matter of when.

**Comment by bjenkinsgit** [comment]
How can we contribute (financially) ?

**Comment by ngbinh** [comment]
as mentioned in Twitter, I would love to contribute to making this happen. Thanks for the awesome work!

**Comment by erinmez** [comment]
@japgolly I would like to donate too. Is this set up somewhere already?

**Comment by japgolly** [comment]
Hi all. I've setup [a patreon page](https://www.patreon.com/japgolly). If you would like to contribute and are able, I'd really appreciate your support. If you know any one else that enjoys this project, my other OSS libraries, or even [my programming blog](https://japgolly.blogspot.com.au/) enough to support me and could reach out to them, that would be tremendously helpful too. Thank you! :bowing_man:

**Comment by nafg** [comment]
BTW I'm using the existing version on 16, so I guess this is about adding new features like essentially returning VdomArray instead of VdomElement? Or am I missing a lot?

**Comment by japgolly** [comment]
@nafg yes, exactly. I need to go through all the React 16.x changelogs and find anything and everything that requires a change here. So adding new features like the portal stuff, adding new VDOM, updating the type-system for new logic/rules (like returning VdomArray from render), etc.

But because React 16 is backwards-compatible with React 15, so too will scalajs-react work with React 16 in a React 15 way.

**Comment by nafg** [comment]
Thanks for the explanation :)

**Comment by japgolly** [comment]
no worries :)

**Comment by japgolly** [comment]
Ok these are the changes required for full React 16 support:

* New render return types
  * arrays
  * strings
  * numbers
  * portals
  * null (how does sjr handle this? should we bother supporting it anyway?)
  * boolean (to support JS syntax *bool && expr* - should we support this? it's ≈ null, even when true)
  * `Option[_]` (Scala version of above)
  * fragments
* Fragments
* Portals
  * `ReactDOM.createPortal`
  * React.Children support for portals (https://github.com/facebook/react/issues/11373)
* "Error boundaries"
  * `componentDidCatch`
* React Addons have been discontinued
  * `react-addons-test-utils` is now `react-dom/test-utils`
  * `perf` doesn't work with 16 - no replacement yet
  * `react-addons-css-transition-group` is now `react-transition-group`, a separate lib
* Deprecated now removed
  * `createClass`
* VDOM
  * Allow on as a custom attribute for AMP. #11153
* Other
  * Calling `setState` with null no longer triggers an update.
    * Support `S => Option[S]`-like patterns, setState filters
  * componentDidUpdate lifecycle no longer receives prevContext param. See #8631 (Don't think sjr is affected)
  * Remember to test module paths with sjs-bundler
  * Depends on requestAnimationFrame (even in test environments). Might need shim: `import 'raf/polyfill'`
  * `ReactDOMServer.renderToNodeStream()` and `ReactDOMServer.renderToStaticNodeStream()`

**Comment by japgolly** [comment]
Two tasks externalised (#448 #449) but otherwise: done! :tada:

**Comment by cquiroz** [comment]
Wow! Thanks 👍 looking forward to use it

**Comment by ngbinh** [comment]
this is awesome!

**Comment by japgolly** [comment]
Cheers! Not long to go

**Comment by nafg** [comment]
Very exciting!

Not to make life more difficult, but note https://medium.com/@baphemot/whats-new-in-react-16-3-d2c9b7b6193b -- in particular,

> The functions that will be in time considered deprecation are:
> [...]
> componentWillReceiveProps — a new function, static getDerivedStateFromProps is introduced

**Comment by japgolly** [comment]
Thanks @nafg. A lifecycle method will only be a 15min change so I'm not too worried about that. I think I'll get 1.2.0 out supporting React 16.2 ASAP, then follow up with a compatible 1.2.1 for React 16.3 when it's released.

**Comment by nafg** [comment]
Thanks. Just make sure you can do it as Props=>State=>State, not just
Props=>State.
